--- #YAML:1.0
name:               Business-OnlinePayment-eSelectPlus
version:            0.07
abstract:           ~
author:
    - Ivan Kohler <ivan-eselectplus@420.am>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Business::OnlinePayment:  0
    Tie::IxHash:          0
    URI::Escape:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
